version: "3"

services:
  frontend:
    build: ./docker/nextjs/
    ports:
      - 3000:3000
    container_name: frontend
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'yarn install && yarn dev'

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

networks:
    default:
      name: app-network
